#ifndef ARTICHOKE_H
#define ARTICHOKE_H

#define MAX_COMBAT_IDLE             (180)
#define RESTED_EXP_FACTOR           (999)
#define TANK_EXP_FACTOR             (150)
#define TANK_DMG_FACTOR             (125)
#define ASSIST_EXP_FACTOR           (25)
#define ASSIST_DMG_FACTOR           (75)

#define ONE_THOUSAND                (1000)
#define TEN_THOUSAND                (10000)
#define HUNDRED_THOUSAND            (100000)
#define ONE_MILLION                 (1000000)
#define TEN_MILLION                 (10000000)
#define HUNDRED_MILLION             (100000000)
#define ONE_BILLION                 (1000000000)

#define COST_FURNACE                (0)
#define COST_RESUME                 (0)
#define COST_SHATTER                (25)
#define COST_SUSPEND                (25)

#define COST_ABJURATION             (100 * ONE_MILLION)
#define COST_ACID_APTITUDE          (100 * ONE_MILLION)
#define COST_BITE_APTITUDE          (250 * ONE_MILLION)
#define COST_BLUNT_APTITUDE         (100 * ONE_MILLION)
#define COST_CHOP_APTITUDE          (100 * ONE_MILLION)
#define COST_CLAW_APTITUDE          (150 * ONE_MILLION)
#define COST_COLD_APTITUDE          (100 * ONE_MILLION)
#define COST_CONJURATION            (100 * ONE_MILLION)
#define COST_DIVINATION             (100 * ONE_MILLION)
#define COST_DRAIN_APTITUDE         (  1 * ONE_BILLION)
#define COST_ELECTRICITY_APTITUDE   (100 * ONE_MILLION)
#define COST_ENCHANTMENT            (100 * ONE_MILLION)
#define COST_EVOCATION              (100 * ONE_MILLION)
#define COST_FIRE_APTITUDE          (100 * ONE_MILLION)
#define COST_ILLUSIONISM            (100 * ONE_MILLION)
#define COST_IMPACT_APTITUDE        (200 * ONE_MILLION)
#define COST_MAGIC_APTITUDE         (100 * ONE_MILLION)
#define COST_NECROMANCY             (100 * ONE_MILLION)
#define COST_PIERCE_APTITUDE        (100 * ONE_MILLION)
#define COST_RESTORATION            (100 * ONE_MILLION)
#define COST_SECOND_LIFE            (  5 * ONE_MILLION)
#define COST_SLASH_APTITUDE         (100 * ONE_MILLION)
#define COST_TRANSMUTATION          (100 * ONE_MILLION)

#define Q_ABJURATION_PROT_LIM      (100000)
#define Q_CONJURATION_KILL_LIM     (1000)
#define Q_CONJURATION_RACES        (({ "horse", "frog", "bear", "wolf" }))
#define Q_DIVINATION_ALIGN_LIM     (ALIGN_PALADINE * 2)
#define Q_ENCHANTMENT_FRIENDLY_LIM (666)
#define Q_ILLUSIONISM_INVIS_LIM    (100)
#define Q_NECROMANCY_ALIGN_LIM     (ALIGN_EVIL * 2)
#define Q_SECOND_LIFE_MAX_HP       (10)
#define Q_SECOND_LIFE_MIN_DAMAGE   (150)
#define Q_TRANSMUTATION_MOD_LIM    (125)

#endif
