#ifndef EMPIRE_H
#define EMPIRE_H

#include <alignment.h>
#include <armour.h>
#include <bits.h>
#include <daemons.h>
#include <feelit.h>
#include <levels.h>
#include <mem.h>
#include <mudlib.h>
#include <origin.h>
#include <room.h>
#include <status.h>
#include <std.h>

#define EMP_DIR                    ("/d/Empire/")
#define EMP_DIR_COM                (EMP_DIR + "com/")
#define EMP_DIR_COM_M              (EMP_DIR_COM + "m/")
#define EMP_DIR_COM_W              (EMP_DIR_COM + "w/")
#define EMP_DIR_DAEMONS            (EMP_DIR + "daemons/")
#define EMP_DIR_ETC                (EMP_DIR + "etc/")
#define EMP_DIR_ETC_ACHIEVEMENTS   (EMP_DIR_ETC + "achievements/")
#define EMP_DIR_ETC_FONTS          (EMP_DIR_ETC + "fonts/")
#define EMP_DIR_ETC_NAMES          (EMP_DIR_ETC + "names/")
#define EMP_DIR_HELP               (EMP_DIR + "help/")
#define EMP_DIR_ISLANDS            (EMP_DIR + "islands/")
#define EMP_DIR_LOG                (EMP_DIR + "log/")
#define EMP_DIR_OBJ                (EMP_DIR + "obj/")
#define EMP_DIR_STD                (EMP_DIR + "std/")
#define EMP_DIR_STD_MOD            (EMP_DIR_STD + "mod/")
#define EMP_DIR_VAR                (EMP_DIR + "var/")
#define EMP_DIR_VAR_BOARDS         (EMP_DIR_VAR + "boards/")
#define EMP_DIR_VAR_EVENTS         (EMP_DIR_VAR + "events/")
#define EMP_DIR_VAR_ISLANDS        (EMP_DIR_VAR + "islands/")

#define EMP_C_ARMOUR               (EMP_DIR_OBJ + "armour")
#define EMP_C_BADGE                (EMP_DIR_OBJ + "badge")
#define EMP_C_BLOOD                (EMP_DIR_OBJ + "blood")
#define EMP_C_CONTAINER            (EMP_DIR_OBJ + "container")
#define EMP_C_ISLANDGEN            (EMP_DIR_OBJ + "islandgen")
#define EMP_C_LIMB                 (EMP_DIR_OBJ + "limb")
#define EMP_C_LIMBLOSS             (EMP_DIR_OBJ + "limbloss")
#define EMP_C_LIQUID               (EMP_DIR_OBJ + "liquid")
#define EMP_C_REINS                (EMP_DIR_OBJ + "reins")
#define EMP_C_STUN                 (EMP_DIR_OBJ + "stun")
#define EMP_C_TASKLIST             (EMP_DIR_OBJ + "tasklist")
#define EMP_C_TOKEN                (EMP_DIR_OBJ + "token")
#define EMP_C_WEAPON               (EMP_DIR_OBJ + "weapon")
#define EMP_C_WOUND                (EMP_DIR_OBJ + "wound")

#define EMP_D_ACHIEVEMENT          (EMP_DIR_DAEMONS + "achievementd")
#define EMP_D_ANARCHY              (EMP_DIR_DAEMONS + "anarchyd")
#define EMP_D_ANIMAL               (EMP_DIR_DAEMONS + "animald")
#define EMP_D_ARMOUR               (EMP_DIR_DAEMONS + "armourd")
#define EMP_D_CLOTH                (EMP_DIR_DAEMONS + "clothd")
#define EMP_D_COLOR                (EMP_DIR_DAEMONS + "colord")
#define EMP_D_COMBAT               (EMP_DIR_DAEMONS + "combatd")
#define EMP_D_CONTAINER            (EMP_DIR_DAEMONS + "containerd")
#define EMP_D_CRITICAL             (EMP_DIR_DAEMONS + "criticald")
#define EMP_D_DEBUG                (EMP_DIR_DAEMONS + "debugd")
#define EMP_D_ENCHANT              (EMP_DIR_DAEMONS + "enchantd")
#define EMP_D_EXP                  (EMP_DIR_DAEMONS + "expd")
#define EMP_D_FONT                 (EMP_DIR_DAEMONS + "fontd")
#define EMP_D_FUR                  (EMP_DIR_DAEMONS + "furd")
#define EMP_D_GEMSTONE             (EMP_DIR_DAEMONS + "gemstoned")
#define EMP_D_GRAPH                (EMP_DIR_DAEMONS + "graphd")
#define EMP_D_LEATHER              (EMP_DIR_DAEMONS + "leatherd")
#define EMP_D_LIMB                 (EMP_DIR_DAEMONS + "limbd")
#define EMP_D_LIST                 (EMP_DIR_DAEMONS + "listd")
#define EMP_D_LOG                  (EMP_DIR_DAEMONS + "logd")
#define EMP_D_METAL                (EMP_DIR_DAEMONS + "metald")
#define EMP_D_NAME                 (EMP_DIR_DAEMONS + "named")
#define EMP_D_QUALITY              (EMP_DIR_DAEMONS + "qualityd")
#define EMP_D_SYMBOL               (EMP_DIR_DAEMONS + "symbold")
#define EMP_D_TIME                 (EMP_DIR_DAEMONS + "timed")
#define EMP_D_TREASURE             (EMP_DIR_DAEMONS + "treasured")
#define EMP_D_WANDER               (EMP_DIR_DAEMONS + "wanderd")
#define EMP_D_WEAPON               (EMP_DIR_DAEMONS + "weapond")
#define EMP_D_WEATHER              (EMP_DIR_DAEMONS + "weatherd")
#define EMP_D_WOOD                 (EMP_DIR_DAEMONS + "woodd")

#define EMP_P_CRITTER              ("emp_critter")
#define EMP_P_IGNORE               ("emp_ignore")
#define EMP_P_LIMBS                ("emp_limbs")
#define EMP_P_NOBLOOD              ("no_blood")
#define EMP_P_NOCRIT               ("no_crit")
#define EMP_P_NOEVENT              ("no_event")
#define EMP_P_NOREGEN              ("no_regen")
#define EMP_P_NOSTUN               ("no_stun")
#define EMP_P_SHOWDEBUG            ("emp_debug")

#define EMP_I_ARMOUR               (EMP_DIR_STD + "armour")
#define EMP_I_COMMAND              (EMP_DIR_STD + "command")
#define EMP_I_DAEMON               (EMP_DIR_STD + "daemon")
#define EMP_I_EVENT                (EMP_DIR_STD + "event")
#define EMP_I_FEELINGS             (EMP_DIR_STD + "feelings")
#define EMP_I_ISLAND               (EMP_DIR_STD + "island")
#define EMP_I_ISLAND_BASE          (EMP_DIR_STD + "island_base")
#define EMP_I_ISLAND_CRITTERS      (EMP_DIR_STD + "island_critters")
#define EMP_I_ISLAND_EVENTS        (EMP_DIR_STD + "island_events")
#define EMP_I_ISLAND_LIVINGS       (EMP_DIR_STD + "island_livings")
#define EMP_I_ISLAND_TIME          (EMP_DIR_STD + "island_time")
#define EMP_I_ISLAND_VIEW          (EMP_DIR_STD + "island_view")
#define EMP_I_ISLAND_WANDER        (EMP_DIR_STD + "island_wander")
#define EMP_I_ITEM                 (EMP_DIR_STD + "item")
#define EMP_I_LOGD                 (EMP_DIR_STD + "logd")
#define EMP_I_SCORED               (EMP_DIR_STD + "scored")
#define EMP_I_MONSTER              (EMP_DIR_STD + "monster")
#define EMP_I_MONSTER_BASE         (EMP_DIR_STD + "monster_base")
#define EMP_I_MONSTER_BORED        (EMP_DIR_STD + "monster_bored")
#define EMP_I_MONSTER_EXP          (EMP_DIR_STD + "monster_exp")
#define EMP_I_MONSTER_FACTION      (EMP_DIR_STD + "monster_faction")
#define EMP_I_MONSTER_GREETING     (EMP_DIR_STD + "monster_greeting")
#define EMP_I_MONSTER_LOGGER       (EMP_DIR_STD + "monster_logger")
#define EMP_I_MONSTER_MESSAGE      (EMP_DIR_STD + "monster_message")
#define EMP_I_MONSTER_RESPONSE     (EMP_DIR_STD + "monster_response")
#define EMP_I_MONSTER_SCARY        (EMP_DIR_STD + "monster_scary")
#define EMP_I_MONSTER_WANDER       (EMP_DIR_STD + "monster_wander")
#define EMP_I_OBJECT               (EMP_DIR_STD + "object")
#define EMP_I_ROOM                 (EMP_DIR_STD + "room")
#define EMP_I_ROOM_BASE            (EMP_DIR_STD + "room_base")
#define EMP_I_ROOM_CRUMB           (EMP_DIR_STD + "room_crumb")
#define EMP_I_ROOM_DESC            (EMP_DIR_STD + "room_desc")
#define EMP_I_SHOP                 (EMP_DIR_STD + "shop")
#define EMP_I_TOKEN                (EMP_DIR_STD + "token")
#define EMP_I_UNLOCKD              (EMP_DIR_STD + "unlockd")
#define EMP_I_WEAPON               (EMP_DIR_STD + "weapon")

#define EMP_I_ALIGNED              (EMP_DIR_STD_MOD + "aligned")
#define EMP_I_ANSI                 (EMP_DIR_STD_MOD + "ansi")
#define EMP_I_ANARCHY              (EMP_DIR_STD_MOD + "anarchy")
#define EMP_I_ARRAY                (EMP_DIR_STD_MOD + "array")
#define EMP_I_CALL_OUT             (EMP_DIR_STD_MOD + "call_out")
#define EMP_I_CAN                  (EMP_DIR_STD_MOD + "can")
#define EMP_I_DESTROY              (EMP_DIR_STD_MOD + "destroy")
#define EMP_I_FILE                 (EMP_DIR_STD_MOD + "file")
#define EMP_I_GRAPH                (EMP_DIR_STD_MOD + "graph")
#define EMP_I_LOCATION             (EMP_DIR_STD_MOD + "location")
#define EMP_I_MATH                 (EMP_DIR_STD_MOD + "math")
#define EMP_I_NOTIFY_FAIL          (EMP_DIR_STD_MOD + "notify_fail")
#define EMP_I_POS                  (EMP_DIR_STD_MOD + "pos")
#define EMP_I_STRING               (EMP_DIR_STD_MOD + "string")
#define EMP_I_TIME                 (EMP_DIR_STD_MOD + "time")
#define EMP_I_UTIL                 (EMP_DIR_STD_MOD + "util")

#define EMP_MAP_PLAYER             ('@')
#define EMP_MAP_DEFAULT            ('?')
#define EMP_MAP_COAST              ('c')
#define EMP_MAP_DESERT             ('d')
#define EMP_MAP_FOREST             ('f')
#define EMP_MAP_HILL               ('h')
#define EMP_MAP_JUNGLE             ('j')
#define EMP_MAP_LAVA               ('l')
#define EMP_MAP_MOUNTAIN           ('m')
#define EMP_MAP_PLAIN              ('p')
#define EMP_MAP_ROAD               ('r')
#define EMP_MAP_SWAMP              ('s')
#define EMP_MAP_TUNDRA             ('t')
#define EMP_MAP_VOID               (' ')
#define EMP_MAP_WATER              ('a')

#define EMP_SEASON_SPRING          (0)
#define EMP_SEASON_SUMMER          (1)
#define EMP_SEASON_AUTUMN          (2)
#define EMP_SEASON_WINTER          (3)

#define EMP_DEBUG(ply, msg)        (EMP_D_DEBUG->debug((ply), (msg)))
#define EMP_LOG(file, msg)         (EMP_D_LOG->log((file), (msg)))
#define EMP_LOGX                   EMP_D_LOG->log

#endif
