#include "/d/Empire/empire.h"

inherit I_DAEMON;

public string 
random_color() 
{
    switch (random(141)) {
    case   0: return "alice blue";
    case   1: return "antique white";
    case   2: return "aqua";
    case   3: return "aquamarine";
    case   4: return "azure";
    case   5: return "beige";
    case   6: return "bisque";
    case   7: return "black";
    case   8: return "blanched almond";
    case   9: return "blue";
    case  10: return "blue violet";
    case  11: return "brown";
    case  12: return "burly wood";
    case  13: return "cadet blue";
    case  14: return "chartreuse";
    case  15: return "chocolate";
    case  16: return "coral";
    case  17: return "cornflower blue";
    case  18: return "cornsilk";
    case  19: return "crimson";
    case  20: return "cyan";
    case  21: return "dark blue";
    case  22: return "dark cyan";
    case  23: return "dark goldenrod";
    case  24: return "dark gray";
    case  25: return "dark green";
    case  26: return "dark khaki";
    case  27: return "dark magenta";
    case  28: return "dark olive green";
    case  29: return "dark orange";
    case  30: return "dark orchid";
    case  31: return "dark red";
    case  32: return "dark salmon";
    case  33: return "dark sea green";
    case  34: return "dark slate blue";
    case  35: return "dark slate gray";
    case  36: return "dark turquoise";
    case  37: return "dark violet";
    case  38: return "deep pink";
    case  39: return "deep sky blue";
    case  40: return "dim gray";
    case  41: return "dodger blue";
    case  42: return "firebrick";
    case  43: return "floral white";
    case  44: return "forest green";
    case  45: return "fuchsia";
    case  46: return "gainsboro";
    case  47: return "ghost white";
    case  48: return "gold";
    case  49: return "goldenrod";
    case  50: return "gray";
    case  51: return "green";
    case  52: return "green yellow";
    case  53: return "honeydew";
    case  54: return "hot pink";
    case  55: return "indian red";
    case  56: return "indigo";
    case  57: return "ivory";
    case  58: return "khaki";
    case  59: return "lavender";
    case  60: return "lavender blush";
    case  61: return "lawn green";
    case  62: return "lemon chiffon";
    case  63: return "light blue";
    case  64: return "light coral";
    case  65: return "light cyan";
    case  66: return "light goldenrod yellow";
    case  67: return "light gray";
    case  68: return "light green";
    case  69: return "light pink";
    case  70: return "light salmon";
    case  71: return "light sea green";
    case  72: return "light sky blue";
    case  73: return "light slate gray";
    case  74: return "light steel blue";
    case  75: return "light yellow";
    case  76: return "lime";
    case  77: return "lime green";
    case  78: return "linen";
    case  79: return "magenta";
    case  80: return "maroon";
    case  81: return "medium aquamarine";
    case  82: return "medium blue";
    case  83: return "medium orchid";
    case  84: return "medium purple";
    case  85: return "medium sea green";
    case  86: return "medium slate blue";
    case  87: return "medium spring green";
    case  88: return "medium turquoise";
    case  89: return "medium violet red";
    case  90: return "midnight blue";
    case  91: return "mint cream";
    case  92: return "misty rose";
    case  93: return "moccasin";
    case  94: return "navajo white";
    case  95: return "navy";
    case  96: return "old lace";
    case  97: return "olive";
    case  98: return "olive drab";
    case  99: return "orange";
    case 100: return "orange red";
    case 101: return "orchid";
    case 102: return "pale goldenrod";
    case 103: return "pale green";
    case 104: return "pale turquoise";
    case 105: return "pale violet red";
    case 106: return "papaya whip";
    case 107: return "peach puff";
    case 108: return "peru";
    case 109: return "pink";
    case 110: return "plum";
    case 111: return "powder blue";
    case 112: return "purple";
    case 113: return "red";
    case 114: return "rosy brown";
    case 115: return "royal blue";
    case 116: return "saddle brown";
    case 117: return "salmon";
    case 118: return "sandy brown";
    case 119: return "sea green";
    case 120: return "sea shell";
    case 121: return "sienna";
    case 122: return "silver";
    case 123: return "sky blue";
    case 124: return "slate blue";
    case 125: return "slate gray";
    case 126: return "snow";
    case 127: return "spring green";
    case 128: return "steel blue";
    case 129: return "tan";
    case 130: return "teal";
    case 131: return "thistle";
    case 132: return "tomato";
    case 133: return "transparent";
    case 134: return "turquoise";
    case 135: return "violet";
    case 136: return "wheat";
    case 137: return "white";
    case 138: return "white smoke";
    case 139: return "yellow";
    case 140: return "yellow green";
    default:  error("Index out of bounds.");
    }
}
